apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneEndpoint:
    host: ""
    port: 0
  {{- if .Values.cluster.helmRelease }}
  helmRelease:
  {{- .Values.cluster.helmRelease | toYaml | nindent 4  -}}
  {{ end }}
  {{if  .Values.cluster.kubernetes_version  }}
  kubernetesVersion: {{ .Values.cluster.kubernetes_version | quote }}
  {{ end }}