name: worker
location: francecentral
clusterResourceGroupName: worker
subscriptionId:
k8sVersion: v1.29.4
sshPublicKey: ""
controlAgentPoolNodes: 2
controlAgentPoolNodeSize: Standard_D2s_v5
workerAgentPoolNodes: 2
workerAgentPoolNodeSize: Standard_D2s_v5
