name: CAPZ Helm Release
on:
  push:
    branches:
      - main
    paths:
    - 'charts/capz/**'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.HELM_RELEASE_TOKEN }}
